-- =======================================================================
-- SQL SCRIPT UTUH DATABASE KOSKU (UAS PEMROGRAMAN MOBILE)
-- Gunakan script ini pada SQL Editor Supabase untuk inisialisasi tabel,
-- relasi, realtime database, trigger otomasi, dan pg_cron.
-- =======================================================================

-- Hapus tabel jika sebelumnya sudah ada (urut berdasarkan ketergantungan FK)
DROP TABLE IF EXISTS public.pengeluaran CASCADE;
DROP TABLE IF EXISTS public.pemasukan CASCADE;
DROP TABLE IF EXISTS public.invoice CASCADE;
DROP TABLE IF EXISTS public.sewa CASCADE;
DROP TABLE IF EXISTS public.request_join CASCADE;
DROP TABLE IF EXISTS public.penyewa CASCADE;
DROP TABLE IF EXISTS public.detail_penyewa CASCADE;
DROP TABLE IF EXISTS public.kamar CASCADE;
DROP TABLE IF EXISTS public.profil_admin CASCADE;

-- 1. TABEL: profil_admin
-- Menampung profil pemilik kos yang terhubung dengan Supabase Auth
CREATE TABLE public.profil_admin (
    id_admin uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nama_lengkap text NOT NULL,
    nama_kost text NOT NULL,
    nomor_wa text,
    foto_profil_url text,
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. TABEL: kamar
-- Menampung daftar kamar kos milik admin
CREATE TABLE public.kamar (
    id_kamar int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_admin uuid NOT NULL REFERENCES public.profil_admin(id_admin) ON DELETE CASCADE,
    nomor_kamar text NOT NULL,
    harga_sewa_dasar int8 NOT NULL,
    status_kamar text NOT NULL CHECK (status_kamar IN ('Kosong', 'Terisi', 'Perbaikan')),
    kode_kamar text UNIQUE NOT NULL,
    fasilitas text[],
    foto_kamar text[]
);

-- 3. TABEL: detail_penyewa
-- Menampung biodata KTP penyewa yang terhubung dengan Supabase Auth
CREATE TABLE public.detail_penyewa (
    nik text PRIMARY KEY,
    id_user uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    tempat_lahir text NOT NULL,
    tanggal_lahir date NOT NULL,
    jenis_kelamin text NOT NULL,
    alamat_ktp text NOT NULL,
    pekerjaan text NOT NULL,
    foto_ktp_url text,
    foto_profil_url text,
    nama_lengkap text,
    nomor_whatsapp text,
    email text
);

-- 4. TABEL: penyewa
-- Menampung data kontak aktif penyewa
CREATE TABLE public.penyewa (
    id_penyewa int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik text NOT NULL REFERENCES public.detail_penyewa(nik) ON DELETE CASCADE,
    nomor_whatsapp text NOT NULL,
    nama_lengkap text NOT NULL
);

-- 5. TABEL: request_join
-- Menampung pengajuan bergabung ke kamar kos dari user ke admin
CREATE TABLE public.request_join (
    id_request int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    id_kamar int8 NOT NULL REFERENCES public.kamar(id_kamar) ON DELETE CASCADE,
    status_request text NOT NULL CHECK (status_request IN ('Menunggu Konfirmasi', 'Disetujui', 'Ditolak')),
    tanggal_pengajuan timestamp with time zone DEFAULT now()
);

-- 6. TABEL: sewa
-- Menampung status kontrak sewa aktif kamar kos
CREATE TABLE public.sewa (
    id_sewa int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kamar int8 NOT NULL REFERENCES public.kamar(id_kamar) ON DELETE RESTRICT,
    id_penyewa int8 NOT NULL REFERENCES public.penyewa(id_penyewa) ON DELETE RESTRICT,
    tanggal_masuk date NOT NULL,
    durasi_bulan int4 NOT NULL,
    status_sewa text NOT NULL CHECK (status_sewa IN ('Aktif', 'Selesai', 'Batal'))
);

-- 7. TABEL: invoice
-- Menampung data tagihan bulanan multi-komponen
CREATE TABLE public.invoice (
    id_invoice int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sewa int8 NOT NULL REFERENCES public.sewa(id_sewa) ON DELETE RESTRICT,
    nomor_invoice text UNIQUE NOT NULL,
    periode_sewa text NOT NULL,
    biaya_sewa_pokok int8 NOT NULL DEFAULT 0,
    biaya_listrik int8 NOT NULL DEFAULT 0,
    biaya_kebersihan int8 NOT NULL DEFAULT 0,
    total_tagihan int8 NOT NULL,
    status_pembayaran text NOT NULL CHECK (status_pembayaran IN ('Lunas', 'Belum Bayar', 'Menunggu Verifikasi')),
    bukti_transfer_url text,
    tanggal_dibuat date NOT NULL,
    tanggal_jatuh_tempo date NOT NULL
);

-- 8. TABEL: pemasukan
-- Jurnal log kas masuk dari invoice lunas
CREATE TABLE public.pemasukan (
    id_pemasukan int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_invoice int8 NOT NULL REFERENCES public.invoice(id_invoice) ON DELETE RESTRICT,
    tanggal_bayar date NOT NULL,
    nominal_masuk int8 NOT NULL,
    metode_bayar text NOT NULL,
    catatan text
);

-- 9. TABEL: pengeluaran
-- Buku catatan log pengeluaran operasional kos
CREATE TABLE public.pengeluaran (
    id_pengeluaran int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_admin uuid NOT NULL REFERENCES public.profil_admin(id_admin) ON DELETE CASCADE,
    kategori text NOT NULL,
    deskripsi text NOT NULL,
    tanggal_keluar date NOT NULL,
    nominal_keluar int8 NOT NULL
);

-- =======================================================================
-- KODE SINKRONISASI REALTIME (SUPABASE PUBLICATION)
-- =======================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE kamar;
ALTER PUBLICATION supabase_realtime ADD TABLE sewa;
ALTER PUBLICATION supabase_realtime ADD TABLE invoice;

-- =======================================================================
-- TRIGGER 1: OTOMATISASI BUAT INVOICE AWAL SETELAH SEWA DIBUAT
-- =======================================================================
CREATE OR REPLACE FUNCTION public.create_initial_invoice()
RETURNS TRIGGER AS $$
DECLARE
    room_price int8;
    room_no text;
    new_invoice_no text;
    periode text;
BEGIN
    SELECT harga_sewa_dasar, nomor_kamar INTO room_price, room_no
    FROM public.kamar
    WHERE id_kamar = NEW.id_kamar;
    
    new_invoice_no := 'INV/' || to_char(NEW.tanggal_masuk, 'YYYYMMDD') || '/KM-' || room_no || '/' || NEW.id_sewa || '-1';
    periode := to_char(NEW.tanggal_masuk, 'Month YYYY');
    
    INSERT INTO public.invoice (
        id_sewa,
        nomor_invoice,
        periode_sewa,
        biaya_sewa_pokok,
        biaya_listrik,
        biaya_kebersihan,
        total_tagihan,
        status_pembayaran,
        tanggal_dibuat,
        tanggal_jatuh_tempo
    ) VALUES (
        NEW.id_sewa,
        new_invoice_no,
        trim(periode),
        room_price,
        0,
        0,
        room_price,
        'Belum Bayar',
        NEW.tanggal_masuk,
        NEW.tanggal_masuk
    );
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_create_initial_invoice ON public.sewa;
CREATE TRIGGER trg_create_initial_invoice
AFTER INSERT ON public.sewa
FOR EACH ROW
WHEN (NEW.status_sewa = 'Aktif')
EXECUTE FUNCTION public.create_initial_invoice();

-- =======================================================================
-- TRIGGER 2: PROTEKSI CHECKOUT (MENCEGAH CHECKOUT JIKA BELUM LUNAS)
-- =======================================================================
CREATE OR REPLACE FUNCTION public.check_unpaid_invoices_before_leave()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status_sewa = 'Selesai' AND OLD.status_sewa != 'Selesai' THEN
    IF EXISTS (
      SELECT 1 FROM public.invoice 
      WHERE id_sewa = NEW.id_sewa 
      AND status_pembayaran != 'Lunas'
    ) THEN
      RAISE EXCEPTION 'Penyewa tidak dapat keluar kos (masa sewa selesai) karena masih memiliki tagihan invoice yang belum dilunasi. Selesaikan pembayaran terlebih dahulu.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_unpaid_invoices ON public.sewa;
CREATE TRIGGER trg_check_unpaid_invoices
BEFORE UPDATE ON public.sewa
FOR EACH ROW
EXECUTE FUNCTION public.check_unpaid_invoices_before_leave();

-- =======================================================================
-- STORED PROCEDURE & pg_cron: GENERATE INVOICE BULANAN OTOMATIS (H-3 JATUH TEMPO)
-- =======================================================================
CREATE OR REPLACE FUNCTION public.generate_monthly_invoices()
RETURNS void AS $$
DECLARE
    r RECORD;
    next_billing_date date;
    generation_date date;
    new_invoice_no text;
    periode text;
BEGIN
    FOR r IN 
        SELECT 
            s.id_sewa,
            s.id_kamar,
            s.id_penyewa,
            s.tanggal_masuk,
            k.harga_sewa_dasar,
            k.nomor_kamar,
            COUNT(i.id_invoice) as invoice_count
        FROM public.sewa s
        JOIN public.kamar k ON s.id_kamar = k.id_kamar
        LEFT JOIN public.invoice i ON s.id_sewa = i.id_sewa
        WHERE s.status_sewa = 'Aktif'
        GROUP BY s.id_sewa, s.id_kamar, s.id_penyewa, s.tanggal_masuk, k.harga_sewa_dasar, k.nomor_kamar
    LOOP
        next_billing_date := (r.tanggal_masuk + (r.invoice_count * interval '1 month'))::date;
        generation_date := (next_billing_date - interval '3 days')::date;
        
        IF CURRENT_DATE = generation_date THEN
            new_invoice_no := 'INV/' || to_char(CURRENT_DATE, 'YYYYMMDD') || '/KM-' || r.nomor_kamar || '/' || r.id_sewa || '-' || (r.invoice_count + 1);
            periode := to_char(next_billing_date, 'Month YYYY');
            
            INSERT INTO public.invoice (
                id_sewa,
                nomor_invoice,
                periode_sewa,
                biaya_sewa_pokok,
                biaya_listrik,
                biaya_kebersihan,
                total_tagihan,
                status_pembayaran,
                tanggal_dibuat,
                tanggal_jatuh_tempo
            ) VALUES (
                r.id_sewa,
                new_invoice_no,
                trim(periode),
                r.harga_sewa_dasar,
                0, 
                0, 
                r.harga_sewa_dasar, 
                'Belum Bayar',
                CURRENT_DATE,
                next_billing_date
            );
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Aktifkan ekstensi pg_cron di schema extensions jika belum ada
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

-- Daftarkan cron job ke scheduler Supabase (Berjalan setiap jam 17:00 UTC / 00:00 WIB)
SELECT cron.unschedule('generate-monthly-invoices-cron');
SELECT cron.schedule(
    'generate-monthly-invoices-cron',
    '0 17 * * *',
    $$ SELECT public.generate_monthly_invoices(); $$
);
