// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDqTn7HWNz2v5rXNd8jxDjPLPCDAsMqE',
    appId: '1:1083650982565:web:b9e011a6d73a9ccd78834c',
    messagingSenderId: '1083650982565',
    projectId: 'kosku-app-91465',
    authDomain: 'kosku-app-91465.firebaseapp.com',
    storageBucket: 'kosku-app-91465.firebasestorage.app',
    measurementId: 'G-FV1FJ6FKX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDImkJ9mSwSjYuaPUaxvwjjf4X7Y5Sljlo',
    appId: '1:1083650982565:android:d67495eade87588e78834c',
    messagingSenderId: '1083650982565',
    projectId: 'kosku-app-91465',
    storageBucket: 'kosku-app-91465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ykoyX5AK-8m15jH7poa__M5LEiaVI8M',
    appId: '1:1083650982565:ios:0bedfade63f54ad478834c',
    messagingSenderId: '1083650982565',
    projectId: 'kosku-app-91465',
    storageBucket: 'kosku-app-91465.firebasestorage.app',
    iosBundleId: 'com.new.packagename',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ykoyX5AK-8m15jH7poa__M5LEiaVI8M',
    appId: '1:1083650982565:ios:e15ce5701526adac78834c',
    messagingSenderId: '1083650982565',
    projectId: 'kosku-app-91465',
    storageBucket: 'kosku-app-91465.firebasestorage.app',
    iosBundleId: 'com.example.kosku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVDqTn7HWNz2v5rXNd8jxDjPLPCDAsMqE',
    appId: '1:1083650982565:web:9ac9d81aec06d1cb78834c',
    messagingSenderId: '1083650982565',
    projectId: 'kosku-app-91465',
    authDomain: 'kosku-app-91465.firebaseapp.com',
    storageBucket: 'kosku-app-91465.firebasestorage.app',
    measurementId: 'G-QQ52BFDFJF',
  );
}
