-- 1. Membuat Tabel KAMAR
CREATE TABLE kamar (
    id_kamar int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_kamar text NOT NULL,
    harga_sewa_dasar int8 NOT NULL,
    status_kamar text NOT NULL
);

-- 2. Membuat Tabel DETAIL_PENYEWA
CREATE TABLE detail_penyewa (
    nik text PRIMARY KEY,
    tempat_lahir text NOT NULL,
    tanggal_lahir date NOT NULL,
    jenis_kelamin text NOT NULL,
    alamat_ktp text NOT NULL,
    pekerjaan text NOT NULL
);

-- 3. Membuat Tabel PENYEWA
CREATE TABLE penyewa (
    id_penyewa int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik text NOT NULL,
    nomor_whatsapp text NOT NULL,
    nama_lengkap text NOT NULL,
    
    -- Membuat Relasi Foreign Key ke tabel detail_penyewa
    CONSTRAINT fk_penyewa_detail FOREIGN KEY (nik) REFERENCES detail_penyewa(nik) ON DELETE CASCADE
);

-- 4. Membuat Tabel SEWA
CREATE TABLE sewa (
    id_sewa int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kamar int8 NOT NULL,
    id_penyewa int8 NOT NULL,
    tanggal_masuk date NOT NULL,
    durasi_bulan int4 NOT NULL,
    status_sewa text NOT NULL,
    
    -- Membuat Relasi Foreign Key
    CONSTRAINT fk_sewa_kamar FOREIGN KEY (id_kamar) REFERENCES kamar(id_kamar) ON DELETE RESTRICT,
    CONSTRAINT fk_sewa_penyewa FOREIGN KEY (id_penyewa) REFERENCES penyewa(id_penyewa) ON DELETE RESTRICT
);

-- 5. Membuat Tabel INVOICE
CREATE TABLE invoice (
    id_invoice int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sewa int8 NOT NULL,
    nomor_invoice text UNIQUE NOT NULL,
    tanggal_dibuat date NOT NULL,
    tanggal_jatuh_tempo date NOT NULL,
    total_tagihan int8 NOT NULL,
    status_pembayaran text NOT NULL,
    
    -- Membuat Relasi Foreign Key
    CONSTRAINT fk_invoice_sewa FOREIGN KEY (id_sewa) REFERENCES sewa(id_sewa) ON DELETE RESTRICT
);

-- 6. Membuat Tabel PEMASUKAN
CREATE TABLE pemasukan (
    id_pemasukan int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_invoice int8 NOT NULL,
    tanggal_bayar date NOT NULL,
    nominal_masuk int8 NOT NULL,
    metode_bayar text NOT NULL,
    
    -- Membuat Relasi Foreign Key
    CONSTRAINT fk_pemasukan_invoice FOREIGN KEY (id_invoice) REFERENCES invoice(id_invoice) ON DELETE RESTRICT
);

-- 7. Membuat Tabel PENGELUARAN
CREATE TABLE pengeluaran (
    id_pengeluaran int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori text NOT NULL,
    deskripsi text NOT NULL,
    tanggal_keluar date NOT NULL,
    nominal_keluar int8 NOT NULL
);

-- =======================================================================
-- KODE OTOMATIS AKTIFKAN REALTIME UNTUK TABEL: kamar, sewa, DAN invoice
-- =======================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE kamar;
ALTER PUBLICATION supabase_realtime ADD TABLE sewa;
ALTER PUBLICATION supabase_realtime ADD TABLE invoice;